### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#29]
It would be nice to have a favicon. Preferably one that is _not_ "Infi" related so that after #22 it's still easy to remix for others without Infi's (trade) marks to land all over the place?

**Comment by LucaScorpion** [comment]
Mogelijk dat een van de topic icons ook goed dienst zou kunnen doen als favicon? Ik zat zelf aan die van ontwikkelprincipes te denken, omdat die ook een beetje een checklist symboliseert die we proberen te beschermen :grin: 

![icon](https://user-images.githubusercontent.com/5592716/156211728-b3b87072-9b8f-45a7-8624-db181d39fa3f.png)

**Comment by jeroenheijmans** [comment]
Hmmm, slimme optie, maar op veel (desktop) devices is de default size 16x16 volgens mij. Het zijn weliswaar svg's, maar echt duidelijk zijn alle icons niet op die size. Even vlotjes naar 16x16 omgezet zien ze er zo uit in Firefox op Win64:

![screenshot van de icons op 16x16 size](https://user-images.githubusercontent.com/1590536/156235766-5f6806e5-00f9-4eea-b621-169c3596c9f0.png)

Geen groot drama, maar t.o.v. de andere favicons in mijn toolbar wel beetje "ineengeperst" ofzo.

**Comment by LucaScorpion** [comment]
Hmm, valid point. Al supporten moderne browsers volgens mij ook grotere formaten (iig 32x32), dan krijg je dit:

![icon32](https://user-images.githubusercontent.com/5592716/156238210-7a7663fd-8d52-4431-b594-50fa477437fd.png)

16px ter vergelijking (mijn interpolation lijkt anders (cubic), wat vgm ook wel helpt):

![icon16](https://user-images.githubusercontent.com/5592716/156238303-140c2d39-c92b-4cc9-9046-51c5a62da07a.png)

**Comment by jeroenheijmans** [comment]
Ze supporten veelal grotere formats, aye, maar (iig op Windows in Chrome/Firefox/Edge) de favicons worden getoond op 16x16 in de bookmarks bar, favorites, en evt address bar.

De betere interpolation zal inderdaad wel helpen (ik had getest door in die andere design branch even in devtools de image met css te schalen naar 16x16, dat werkt wsch minder goed).

Iets is natuurlijk ook al snel beter dan niets :) dus wellicht moeten we als stopgap 't gewoon doen? Moeten we denk ik wel even met de fill en de kleuren en de transparency sleutelen?

----

Ik heb zelf nog een paar pogingen gewaagd, maar ben duidelijk geen kunstenaar 😂....

![image](https://user-images.githubusercontent.com/1590536/156257472-f5fc7cfa-7f40-4d09-891b-021c85894b2e.png) (moet een tangram zijn)

![image](https://user-images.githubusercontent.com/1590536/156257527-95a825f8-d7bb-4e3e-9184-868209026e12.png) (geforceerde witte achtergrond)

![image](https://user-images.githubusercontent.com/1590536/156257568-4153ff7a-c822-4057-9378-493300dcb658.png) (transparante achtergrond)

![image](https://user-images.githubusercontent.com/1590536/156258532-c11f32b2-20d4-47db-b3a8-e404e7e5b9e2.png) (lijntjes dan maar geprobeerd)

Goed, bovenstaande maakt misschien wel pijnlijk duidelijk dat ik niet artistiek aangelegd ben (en ook geen oefening in die hoek heb), maar geeft me wel het gevoel dat in de _goede_ handen er een geinig logo te maken moet zijn.

Maar laat ons dat er niet van weerhouden om voor nu een bestaand icon als 'goed genoeg' te pakken 😄

**Comment by LucaScorpion** [comment]
Ik moet zeggen dat ik je handcrafted icons helemaal niet zo gek vind, en imo al een stuk beter als stopgap solution dan een topic icon. Ik zie best wel wat in ![](https://user-images.githubusercontent.com/1590536/156257568-4153ff7a-c822-4057-9378-493300dcb658.png), al dan niet met witte achtergrond. (Ik heb GH zelf op dark theme, en daarbij werkt het ook prima, dus transparant is denk ik fine.)
