### ISSUE TITLE
Host our own fonts

### ISSUE THREAD

**Issue by LucaScorpion** [infi-nl/the-infi-way#30]
In our current setup we point in our CSS to Google Fonts. Would be good and nicer to host them ourselves, so we're not dependent on Google, nor indirectly shipping our visitor's data to Google.

**Comment by jeroenheijmans** [comment]
Helemaal mee eens!

**Comment by LucaScorpion** [comment]
Mogelijk is het een goed idee om geen externe fonts te gebruiken, maar een goede lijst van system fonts te kiezen die op de meeste systemen beschikbaar zijn.
