### ISSUE TITLE
Language switching improvements

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#38]
Before any broader public beta gets published and announced, we want to make some changes to the language situation:

- [x] Change the default language to English
- [x] Improve the UI and UX of the language switch by moving it to the top of the page and adding some color or (literal) flags or other visual indicator
- [x] Change the URL structure so that it becomes `/` (defaults to English), `/en/` and `/nl/`

**Comment by LucaScorpion** [comment]
All finished in #59 (big thanks to @h-five-e), so I'm closing this :)
