### ISSUE TITLE
Replace "Infi" in texts with "we" where reasonable

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#40]
We want to make this setup more useful to a broader audience, so we want to replace "Infi" with a broader term where possible. For example:

https://github.com/infi-nl/the-infi-way/blob/91bb76996a6043e77fb98190e2a453c3273d055f/content/en.json#L186

Here we can update it to something like:

> We regularly want to work in the same location our client works at

Or something more terse, but in any case something with "We" so others outside Infi will also be able to identify with it.

**Comment by jeroenheijmans** [comment]
Still need to check if the merged PR fixed all occurrences already, or if there's still a few to do's left.

**Comment by yougotdirked** [comment]
This already seems to have been completed, correct?

**Comment by yougotdirked** [comment]
Seems to be fine, I think this issue should be closed.

**Comment by suzaninfi** [comment]
Agree, the PR has been merged so it all looks good
