### ISSUE TITLE
Super basic non-fishy analytics for way.infi.nl

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#42]
We want to have non-personally-identifyable analytics, things only needed to help us improve our setup. You should think about:

- Info about which Devices, Clients and OS'es are being used
- How many times it's viewed, differentiated per language

Certainly _not_ something like Google Analytics, _maybe_ something like self-hosted Matomo, but most likely (at the start) just something simple like Web Server logs will do.

The goal is to be able to improve the setup and content according to who visits us, without any tracking nonsense.

Technical note from our discussion about this: perhaps it's worth switching from GitHub Pages hosting to something slightly different? Netlify, possibly?

**Comment by LucaScorpion** [comment]
I've really only used GH pages and Netlify as static site hosts, which both have served me really well, with GH definitely being more basic in terms of what it can do. For Netlify it's straightforward enough:

![image](https://user-images.githubusercontent.com/5592716/181213918-3f1cb903-3f52-4f9d-ad93-dea568ca05a3.png)

Which I think would be worth it?

**Comment by jeroenheijmans** [comment]
Agreed... but only if we'd actually use it, I think? So something to do only short moments before we start to do a bigger push for The Way?

**Comment by LucaScorpion** [comment]
Fair enough yeah. Although making the switch a bit earlier might be good, so we're sure Netlify works to our liking ;) Since it's an open source repo the basics are free, and we should be able to enable analytics later.

**Comment by jeroenheijmans** [comment]
I'm 100% fine with that. We'd just have to switch up our DNS setup as part of the switch.

**Comment by LucaScorpion** [comment]
I've got Netlify working: https://the-infi-way.netlify.app/ (credentials are in bitwarden btw). Custom domains and DNS settings can be found under "Site settings" -> "Domain management". I've already added the way.infi.nl domain, but we just need to update our DNS settings to make it work. Could you take care of that?

Also as a completely unrelated side note, I still love how fast this build setup is :smile: 

![image](https://user-images.githubusercontent.com/5592716/181783474-2eb2409b-99e5-407f-9460-9beed3060cde.png)

**Comment by jeroenheijmans** [comment]
Haha that's one hellofa build pipeline indeed! :)

Let's take the DNS discussion to internal Slack for a moment? Otherwise all good.

**Comment by LucaScorpion** [comment]
This is now done by adding way.infi.nl to our Matomo in #103, so closing this issue.
