### ISSUE TITLE
Design verbeteren

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#6]
Het eerste (alfa) design (zie onder) is "okay" voor een eerste opzet, en geeft wat richting aan voor een mogelijk definitief design. Maar het behoeft _op z'n minst_ een review en touch-up van een extra paar ogen, of wellicht zelfs een re-vamp? Ook een functioneel design mag er immers aantrekkelijk uit zien!

Ter illustratie, we hebben nu:

![screenshot van de index.html file](https://user-images.githubusercontent.com/1590536/118405773-91e60100-b679-11eb-8717-c0317ff7c970.png)

**Comment by jeroenheijmans** [comment]
Nog wat feedback via-via:

> Dark mode (evt met CSS Media Queries? 🤩), mogelijk zelfs als default design?

**Comment by LucaScorpion** [comment]
Deze lijkt me af zo :) Ik heb wel een nieuw issue aangemaakt voor een light mode: https://github.com/infi-nl/the-infi-way/issues/33
