### ISSUE TITLE
Printer-friendly version

### ISSUE THREAD

**Issue by dirkinfi** [infi-nl/the-infi-way#70]
We want to reach as many people as possible with 'The Infi Way'. A subset of people will want to print the document. 

Currently, there are these issues:
1. Black background: in the print-outs Christa used when carrying out her Infi-way session, the background of the print was solid-black. This is tremendously wasteful for ink. (Note: I'm not sure how she made the prints, since in my tests the prints were always grey text on white background; I suspect she used screenshot because of issue 2. Need to ask her if necessary.)
2. Browsers mess up the printing in different ways: (all tested on my mac)
- Safari: huge font, lots of white space due to the column setup
- Firefox: big empty circles where the graphics would have been
- Chrome: big empty circles where the graphics would have been; plus rendering the printer preview for some reason takes ages

Solution suggestion:
In order to promote printing and PDF-sharing of the Infi-way, while printing (or PDF-exporting)
1. remove solidblack background (and adjust font-color accordingly, 
2. strip unnecessary graphics, 
3. render the information hierarchy without relying on columns (to prevent white-space)
4. use a 'normal' font-size
5. (print the full links, since this website is rather link-heavy so the print will loose quite some info?)

**Comment by jeroenheijmans** [comment]
Thanks for this @dirkinfi, great suggestion! Have run into this myself as well. Most browsers indeed ignore black/dark backgrounds but then still some optimization is needed to make print versions _nice_.

There's `@media` rules for print CSS that can easily fix this, so this would be a great addition! See also the [paged media](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_paged_media) documentation, I think there are some workarounds needed to ensure headers stick with their respective sections on a page, but that would be a stretch goal.

Whomever picks this up, take care that in #64 related (but very different) changes are being made, it would be good to take a few extra steps to avoid merge conflicts.
