### ISSUE TITLE
Improve collapse/expand feature

### ISSUE THREAD

**Issue by jeroenheijmans** [infi-nl/the-infi-way#73]
## The problem

There's a toggle button at the top-right of each block like this:

![partial screenshot of a single block of content, circling an upward-triangle button](https://github.com/infi-nl/the-infi-way/assets/1590536/0f946c18-2d59-4aa0-9c22-139a24cb8e01)

This feature is nice, but there are a few problems with this:

- It's not very discoverable
- The button has no clear affordance
- The button is repeated for each block, but any one of them toggles collapse/expand for _all_ blocks
- The ARIA attributes for explaining the collapsed or expanded state are missing

Surely there's multiple ways to improve this?

PS. This came out of #69 and offline discussions with @dirkinfi (who personally also prefers to see a collapsed version by default).

**Comment by jeroenheijmans** [comment]
## Proposed solution

One way to improve this situation is:

- remove the individual buttons, and instead making it a page-level toggle
- toggle could be placed in the header, near the Language switch (and the light/dark mode switch which is in progress in #33) 
- toggle could also cause an update to the query or hash part of the URL, to allow hotlinking to a collapsed or expanded version
- toggle could be persisted in e.g. localStorage
- toggle could get a more clear affordance in this area as well

Personally I think it's all upsides and no down sides. Curious to hear other people's thoughts?

**Comment by dirkinfi** [comment]
I don't have time nor mental space to process this. I'd need to see this work. But anything is an improvement to the current functionality I guess ;-)
