### ISSUE TITLE
Update email address to community email address. 

### ISSUE THREAD

**Issue by DannyvdSluijs** [infi-nl/the-infi-way#89]
As it says on the tin. We should update the email address from jeroen’s work email to community@infi.nl. Same as we do on the Inficon website (https://con.Infi.nl)

When making changes be aware the email address is mentioned two times
- https://github.com/infi-nl/the-infi-way/blob/main/template.html#L382
- https://github.com/infi-nl/the-infi-way/blob/main/template.html#L400

**Comment by jeroenheijmans** [comment]
Very fair! I'll kick off a quick out-of-GitHub discussion on this topic, and report back here with what we decided to do.
